/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { DeBank } from "./DeBank";
export type { DeBankLending } from "./DeBankLending";
export type { DeBankStaking } from "./DeBankStaking";
